"""Add email and verification fields to User; add DocumentVerification model

Revision ID: 01a36cdb8633
Revises: add_draft_bills_and_staffers
Create Date: 2025-11-07 10:49:01.420166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a36cdb8633'
down_revision = 'add_draft_bills_and_staffers'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_verifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('bill_supports', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_bill_supports_bill_number'), ['bill_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_supports_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('fk_bill', type_='foreignkey')
        batch_op.drop_constraint('fk_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_bill_supports_bill', 'bills', ['bill_number'], ['bill_number'])
        batch_op.create_foreign_key('fk_bill_supports_user', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('comment_supports', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_comment_supports_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_supports_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('fk_comment', type_='foreignkey')
        batch_op.drop_constraint('fk_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_supports_comment', 'comments', ['comment_id'], ['id'])
        batch_op.create_foreign_key('fk_comment_supports_user', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('run_supports', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_run_supports_candidate_user_id'), ['candidate_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_supports_supporter_user_id'), ['supporter_user_id'], unique=False)
        batch_op.drop_constraint('fk_supporter', type_='foreignkey')
        batch_op.drop_constraint('fk_candidate', type_='foreignkey')
        batch_op.create_foreign_key('fk_run_supports_candidate', 'users', ['candidate_user_id'], ['id'])
        batch_op.create_foreign_key('fk_run_supports_supporter', 'users', ['supporter_user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.create_foreign_key('fk_users_rep_boss', 'representatives', ['rep_boss_id'], ['id'])
        batch_op.create_foreign_key('fk_users_representative', 'representatives', ['representative_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_verification_sent_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email')

    with op.batch_alter_table('run_supports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_candidate'), 'users', ['candidate_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_supporter'), 'users', ['supporter_user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_run_supports_supporter_user_id'))
        batch_op.drop_index(batch_op.f('ix_run_supports_candidate_user_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('comment_supports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment'), 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_comment_supports_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_supports_comment_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('bill_supports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_bill'), 'bills', ['bill_number'], ['bill_number'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_bill_supports_user_id'))
        batch_op.drop_index(batch_op.f('ix_bill_supports_bill_number'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('document_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_verifications_user_id'))

    op.drop_table('document_verifications')
    # ### end Alembic commands ###
