"""Initial migration

Revision ID: c77eb2aba228
Revises: 
Create Date: 2025-11-06 12:39:35.835887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77eb2aba228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('apt_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('address_verified', sa.Boolean(), nullable=False))
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('zipcode',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('address_verified')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('apt_unit')
        batch_op.drop_column('street_address')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
